### ISSUE TITLE
Does not compile in raspbian

### ISSUE THREAD

**Issue by Sod-Almighty** [soemraws/cl-libusb#5] opened 2019-09-21 19:39 UTC
I am running Raspbian and have installed libffi-dev, but this library will not compile. Am I missing something?
```
* (load "~/quicklisp/setup.lisp")

T
* (ql:quickload :cl-libusb)
To load "cl-libusb":
  Load 1 ASDF system:
    cl-libusb
; Loading "cl-libusb"
.; pkg-config libffi --cflags

; cc -marm -o /root/.cache/common-lisp/sbcl-1.3.7.debian-linux-arm/usr/share/common-lisp/source/cl-cffi/libffi/libffi-types__grovel-tmp7LQ0A0VI -I/usr/share/common-lisp/source/cl-cffi/ /root/.cache/common-lisp/sbcl-1.3.7.debian-linux-arm/usr/share/common-lisp/source/cl-cffi/libffi/libffi-types__grovel.c
/root/.cache/common-lisp/sbcl-1.3.7.debian-linux-arm/usr/share/common-lisp/source/cl-cffi/libffi/libffi-types__grovel.c: In function ‘main’:
/root/.cache/common-lisp/sbcl-1.3.7.debian-linux-arm/usr/share/common-lisp/source/cl-cffi/libffi/libffi-types__grovel.c:82:41: error: ‘FFI_UNIX64’ undeclared (first use in this function)
   fprintf(output, "%"PRIiMAX, (intmax_t)FFI_UNIX64);
                                         ^~~~~~~~~~
/root/.cache/common-lisp/sbcl-1.3.7.debian-linux-arm/usr/share/common-lisp/source/cl-cffi/libffi/libffi-types__grovel.c:82:41: note: each undeclared identifier is reported only once for each function it appears in
While evaluating the form starting at line 21, column 0
  of #P"/root/quicklisp/dists/quicklisp/software/gsll-quicklisp-eeeda841-git/gsll.asd":

debugger invoked on a ASDF/FIND-SYSTEM:LOAD-SYSTEM-DEFINITION-ERROR: Error while trying to load definition for system gsll from pathname /root/quicklisp/dists/quicklisp/software/gsll-quicklisp-eeeda841-git/gsll.asd: Subprocess (:PROCESS #<SB-IMPL::PROCESS :EXITED 1>)
 with command ("cc" "-marm" "-o" "/root/.cache/common-lisp/sbcl-1.3.7.debian-linux-arm/usr/share/common-lisp/source/cl-cffi/libffi/libffi-types__grovel-tmp7LQ0A0VI" "-I/usr/share/common-lisp/source/cl-cffi/" "/root/.cache/common-lisp/sbcl-1.3.7.debian-linux-arm/usr/share/common-lisp/source/cl-cffi/libffi/libffi-types__grovel.c")
 exited with error code 1
```

```
# uname -a
Linux raspberrypi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l GNU/Linux

# cat /etc/issue
Raspbian GNU/Linux 9 \n \l

# dpkg -l | grep libffi
ii  libffi-dev:armhf                      3.2.1-6                           armhf        Foreign Function Interface library (development files)
ii  libffi6:armhf                         3.2.1-6                           armhf        Foreign Function Interface library runtime
```

**Comment by soemraws** [comment] 2019-09-28 16:13
With this error too, I'm wondering if this is an issue with libusb-ffi or with cffi using libffi. I cannot reproduce this error as I don't have a rpi, but the errors seem to be in the libffi files of cffi.

So again, I would advise you to check with the cffi project.

**Comment by Sod-Almighty** [comment] 2019-09-29 14:46
I can quickload cffi without issue.

Would it help if I gave you remote SSH access to a rpi?

**Comment by soemraws** [comment] 2019-10-12 12:06
I'm sorry to say that while it may help, I simply do not have the time to look into it. Moreover, I haven't used this library for a very long time, I don't think I even have libusb-0.1 still on my system.

Effectively, I think this project would be abandoned for now, until I have a new need to use it, and then I'd probably rewrite it (or at least add to it) to use libusb-1.0.

**Comment by Sod-Almighty** [comment] 2019-10-12 12:31
I see. Well, if you find the time, please let me know on here. It would take me a few hours to set up a Pi for remote access.

**Comment by soemraws** [comment] 2019-12-22 04:13
I've made a new branch called static-vectors. It uses static-vectors instead of foreign-arrays. The reason for the switch is that foreign-arrays used antik and all sorts of non-essential other dependencies, without it being needed to use libusb (e.g. gsll, cl+ssl).

While this switch will break software dependent on cl-libusb due to differences in calls to usb-bulk-* and usb-interrupt-* read and write functions, could you nevertheless try to see if it at least compiles?

**Comment by Sod-Almighty** [comment] 2019-12-22 19:02
Thank you. The library seems to compile now. (Sadly I can't fully test it in my project because now I find that [lisp-binary](https://github.com/j3pic/lisp-binary) crashes sbcl on the Pi, apparently. But I believe your fix works.)

**Comment by soemraws** [comment] 2019-12-23 00:23
Just to be clear, the fix may work for the compilation issues, but it may not work in whatever way it was used in the project that you used it in. Specifically, due to the usage of static vectors vs foreign arrays. I'm willing to log in one of these days (it will probably be after christmas) to have a closer look. Let me know.

I would prefer to merge the static-vectors branch into master, however it is not compatible, and am not sure how I would have to deal with that in a good way. Currently, I just want to see that it works (e.g. on your rpi project) and then merge, with additional remarks in the README so that people can port their project to use the new version.

**Comment by Sod-Almighty** [comment] 2019-12-23 20:49
I'm having a little difficulty using this patch. Obviously I can't do `(ql:quickload :cl-libusb)` because it would look in the quicklisp cache. However, if I just `(load "cl-libusb/cl-libusb.lisp")` and suchlike, it complains `Unknown CFFI type (:STRUCT BUS)`. It's clearly not doing the grovel step.

What is the correct way to load the library from a local directory rather than using quicklisp, please?

**Comment by soemraws** [comment] 2019-12-24 02:38
If you are using SBCL and you placed this directory somewhere where ASDF can find it, you can simpy do a (require "CL-LIBUSB"), which will compile and load the system. Please let me know if it works with modifications to your own code to use static vectors.

**Comment by Sod-Almighty** [comment] 2019-12-24 05:30
Unfortunately, "in the current directory" seems to be a place ASDF refuses point-blank to look:

`(require 'cl-libusb)`
> Don't know how to REQUIRE CL-LIBUSB.

`(asdf:oos 'asdf:load-op :cffi-grovel)`
> Component :CFFI-GROVEL not found

And so on.

Apparently the "idiomatic way" to make ASDF find your library is to put it in some global system-defined location; which is all very well if the library is an official distro, but no damn use if it's a testing branch or a downloaded zip file.

It seems I *can* use a legacy method to force ASDF to look where I want, though. At least, until the maintainers of ASDF decide to remove it.
```
(defun abspath (path-string)
  (uiop:unix-namestring (uiop:merge-pathnames* (uiop:parse-unix-namestring path-string))))
(push (abspath "") asdf:*central-registry*)
(require 'cl-libusb))
```
Having done that, it does appear to work and detect the USB device on a Raspberry Pi.

**Comment by soemraws** [comment] 2019-12-24 12:56
You can also simply remove cl-libusb from quicklisp/dists/quicklisp/software, then clone the repository into quicklisp/local-projects/cl-libusb. This way, quicklisp will find your version of cl-libusb.

Meanwhile, I hear that this branch compiles and runs on Raspberry Pi. I will close this issue and after some minor adjustments, merge it into master.

**Closed by soemraws** 2019-12-24 12:56 UTC
